/**
 * Help texts for the autorole feature. The no-topic text is the beginners
 * guide; each topic documents one subcommand group of /autorole.
 */

export const AUTOROLE_GUIDE = [
  '# Autorole — beginners guide',
  '',
  'Autorole links Discord members to their WarEra accounts, then keeps their roles and nicknames in sync with the game automatically.',
  '',
  '**How linking works**',
  '1. A member runs `/link start account:<name/id/url>` (or clicks a posted **Link WarEra** button).',
  "2. **Country check** — if their WarEra citizenship is on the allowed list (`/autorole country list`), or they hold a *proxy role*, they continue directly. Otherwise the request is posted to the review channel where staff **Approve**/**Deny** it.",
  '3. **Verification** — the bot DMs a 6-digit code; the member renames one of their WarEra companies to that code and presses the DM button (or runs `/link verify`). Approved-by-staff members go through this same step. Servers can skip it entirely with `config set skip_verification:True`.',
  '4. **Linked** — the member is synced immediately and then on every cycle.',
  '',
  '**What sync does** (per linked member, every `interval_seconds`)',
  '- Grants the highest level role they qualify for (`levelrole`)',
  '- Grants an eco/war/hybrid build role from their skill spread (`buildrole`)',
  '- Grants the role mapped to their military unit (`murole`)',
  '- Removes roles from members inactive too long (`timedrole`)',
  '- Sets their nickname to `<WarEra name> (<MU>)` — or `(TBD)` plus a DM nudge if their MU is not mapped',
  '- Never touches roles listed as protected (`config protectedroles`)',
  '',
  '**Quick setup**',
  '1. `/autorole country add id:<countryId>` — who may link without review',
  '2. `/autorole config set review_channel:#channel` — where review requests go',
  '3. `/autorole levelrole add`, `/autorole buildrole set`, `/autorole murole set` — the roles to manage',
  '4. `/autorole linkmessage post` — a permanent Link button for members',
  '5. `/autorole sync now` — first sync; `/autorole sync status` to check on it',
  '',
  '**Topics:** run `/autorole help topic:<name>` for details on: levelrole, timedrole, buildrole, murole, country, links, config, sync, linkmessage.',
].join('\n');

export const AUTOROLE_TOPIC_HELP: Record<string, string> = {
  levelrole: [
    '## /autorole levelrole — roles granted by WarEra level',
    '',
    'Each entry grants a role at (and above) a WarEra level. On every sync a member receives the entry with the **highest `min_level` they qualify for**, and the other configured level roles are removed (protected roles excepted).',
    '',
    '- `add role:<role> min_level:<n>` — add or update an entry',
    '- `remove role:<role>` — delete an entry',
    '- `list` — show all entries',
    '',
    'Example ladder: Private @ 2, Lieutenant @ 5, Captain @ 10 — a level 7 member gets Lieutenant only.',
  ].join('\n'),

  timedrole: [
    '## /autorole timedrole — inactivity role removal',
    '',
    "Removes a role from members who haven't connected to WarEra for a number of days (based on the game's last-connection timestamp). **Removal only** — the role is never re-added by sync; something/someone else must grant it back.",
    '',
    '- `add role:<role> days:<n>` — remove the role after n days offline',
    '- `remove role:<role>` — delete the rule',
    '- `list` — show all rules',
  ].join('\n'),

  buildrole: [
    '## /autorole buildrole — eco/war/hybrid build roles',
    '',
    'Classifies each linked member by where their skill points sit and grants one build role:',
    '- **Eco skills:** companies, entrepreneurship, production, management',
    '- **War skills:** attack, armor, precision, dodge, criticalChance, criticalDamages, lootChance',
    '',
    'If eco% ≥ eco threshold → eco role; else war% ≥ war threshold → war role; else → hybrid role. Members with no spent points get no build role.',
    '',
    '- `set [eco_role] [war_role] [hybrid_role] [eco_threshold] [war_threshold]` — only passed options change',
    '- `clear which:<eco|war|hybrid|all>` — unset roles',
    '- `view` — show current configuration',
  ].join('\n'),

  murole: [
    '## /autorole murole — military unit roles',
    '',
    "Maps a WarEra military unit to a Discord role. On sync a member gets the role mapped to their current MU; other mapped MU roles are removed. The MU's name also appears in their nickname: `<WarEra name> (<MU name>)`.",
    '',
    'Members whose MU is **not** mapped (or who have none) are nicknamed `(TBD)` and receive a DM nudge to join an official MU (at most once per 24h).',
    '',
    '- `set role:<role> mu:<id or app.warera.io/mu/... link>` — the MU name is fetched and stored automatically',
    '- `remove mu:<id>` — delete a mapping',
    '- `list` — show all mappings',
  ].join('\n'),

  country: [
    '## /autorole country — the linking allowlist',
    '',
    'WarEra country ids whose citizens may link **without staff review** (they still do company verification unless that is disabled). Members from any other country go to the review channel for Approve/Deny.',
    '',
    'Members holding a *proxy role* (`/autorole config proxyroles`) bypass this check entirely.',
    '',
    '- `add id:<countryId>` / `remove id:<countryId>` / `list`',
  ].join('\n'),

  links: [
    '## /autorole links — manage linked members',
    '',
    '- `list` — every linked member and their WarEra id',
    '- `full` — the same, enriched with live level/country/build (slower; one API sweep)',
    '- `pending` — link requests awaiting review',
    '- `approve user:<member>` — approve a pending request; the member is then DMed a verification code and must still rename a company to finish',
    '- `deny user:<member> [reason]` — reject a request (reason is DMed to them)',
    '- `unlink user:<member>` — remove a link or pending request',
    '',
    'Approve/Deny also exist as buttons on each review-channel message; they require the Administrator permission, a configured staff role/user, or the guild owner.',
  ].join('\n'),

  config: [
    '## /autorole config — general settings',
    '',
    '- `view` — dump the full configuration',
    '- `set [review_channel] [skip_verification] [interval_seconds] [enabled] [sync_nicknames] [unlinked_role] [clear_unlinked_role]` — only passed options change',
    '  - `review_channel` — where out-of-country link requests are posted',
    '  - `skip_verification` — link immediately without the company-rename step',
    '  - `interval_seconds` — how often the periodic sync runs (min 60)',
    '  - `enabled` — pause/resume the periodic sync',
    '  - `sync_nicknames` — let sync manage nicknames or leave them alone',
    '  - `unlinked_role` — role given to members who have not linked; assigned on join and once via a backfill sweep, and removed the moment they link. Needs the Server Members privileged intent.',
    '  - `clear_unlinked_role` — stop assigning it (existing holders keep the role until you remove it manually)',
    '- `staffroles role1..role5` / `staffusers users:<ids>` — who may act on review buttons (replaces the list; empty clears)',
    '- `proxyroles role1..role5` — roles that bypass the country check when linking',
    '- `protectedroles role1..role5` — roles the sync must never remove',
  ].join('\n'),

  sync: [
    '## /autorole sync — running and inspecting the sync',
    '',
    'The bot checks every minute whether a server is due (per its `interval_seconds`) and then syncs all linked members in one batched API sweep.',
    '',
    '- `now [user]` — sync everyone immediately, or just one member',
    '- `status` — enabled state, linked/pending counts, interval, last sync time',
  ].join('\n'),

  linkmessage: [
    '## /autorole linkmessage — the permanent Link button',
    '',
    'Posts a **Link WarEra** button message that members can always use instead of `/link start`; clicking it opens a form asking for their WarEra username/id/URL and then follows the normal linking flow.',
    '',
    '- `post [channel]` — post the button (defaults to the current channel); one per channel is tracked',
    '- `remove [channel]` — delete the tracked button message',
  ].join('\n'),
};

export const LINK_HELP = [
  '# /link — connect your WarEra account',
  '',
  'Linking lets the server sync your roles and nickname with your WarEra profile.',
  '',
  '**The flow**',
  '1. `/link start account:<your WarEra username, id, or profile URL>`',
  "2. If your country is on the server's allowed list (or staff approve your request), the bot DMs you a **6-digit code**.",
  '3. In WarEra, rename one of your companies to exactly that code.',
  "4. Press **I've renamed my company** in the DM (or run `/link verify`). Done — you can rename the company back.",
  '',
  "If your country is not allowed, your request goes to the server's staff for review first — you'll be DMed the outcome.",
  '',
  '**Commands**',
  '- `start account:<...>` — begin linking',
  '- `verify` — re-check your company rename if the DM button is unavailable',
  '- `unlink` — remove your link, or cancel a pending request/verification',
  '- `whoami` — your current link status (including an active code and its expiry)',
  '- `whois user:<member>` or `whois account:<warera>` — see who a member/account is linked to',
  '- `help` — this message',
].join('\n');
